### ISSUE TITLE
TODO Alpha

### ISSUE THREAD

**Issue by JeromSar** [derpfacedirk/Goldiriath#5]
- [ ] Lots of bug testing
- [ ] Quest writing
- [ ] Document everything: #42
- [ ] Resource pack fixing: https://github.com/Goldiriath/Configuration/issues
- [ ] **Prepare the map**: #75 
- [ ] **Skills**: #6
- [x] **Disable player interactions**: #73 
- [x] **Texturing**: #46 [wiki/Texturing](https://github.com/Goldiriath/Goldiriath/wiki/Texturing)
- [x] Developer Mode https://github.com/Goldiriath/Goldiriath/commit/8f8cff0e3818a8c0b7d80a1fa22930ce27486cc6
- [x] AutoClose System https://github.com/Goldiriath/Goldiriath/commit/c36830b185a93fbc58a3e5c85b72607c4420bd6f
- [x] InfiniteDispensers https://github.com/Goldiriath/Goldiriath/commit/089738ff943b90da90f53e4fae97d5f91ca1794a
- [x] **Shop System**: #41
- [x] **Damage Implementation**: #57 
- [x] **Wand + Basic attack**
- [x] **Loot Tables**: #8
- [x] **Quests**: #1
- [x] **Inventory Handling**: #39
- [x] **Aggro System**: #40
- [x] **MetaCycler reimplementation** https://github.com/Goldiriath/Goldiriath/commit/9cf2caa6a759d7062d07cb6e0ef54440d5aa7baa https://github.com/Goldiriath/Goldiriath/commit/7d0c5857d29ff8ed0f4de639cc6e08be8afce5a4
- [x] **MobSpawns**
  - [x] Implement MobSpawn mechanics https://github.com/derpfacedirk/Goldiriath/commit/c2019d0f45e992fdc75f5dba62c11b7e0b75868c
  - [x] Implement sign-based Mobspawn system https://github.com/derpfacedirk/Goldiriath/commit/627c93b536b5f27ed8cee813d69b1153c6f7cc26
  - [x] Implement MobSpawn deletion https://github.com/derpfacedirk/Goldiriath/commit/1b95f25f0e0fefb6422cc5f3d374f10cddde320c
  - [x] Configurable mob armor. https://github.com/derpfacedirk/Goldiriath/commit/ab0780a02332bf453cce090894a288ddca0405a4 https://github.com/derpfacedirk/Goldiriath/commit/414c228bf55817bda22f0c933b2a6b921ac05719
  - [x] Disable mobspawns when no players are nearby. https://github.com/Goldiriath/Goldiriath/commit/259ed9cad64deb69655c803588ae42b102d233b5
  - [x] Potion effects https://github.com/Goldiriath/Goldiriath/commit/c5dc35b608b1e242d943c27127cad973d30e6f9d
  - [x] Store level in mob metadata https://github.com/Goldiriath/Goldiriath/commit/08a20c0da961f39543a0b5e7722c6b883910e07a
  - [x] Kill mobs on disable https://github.com/Goldiriath/Goldiriath/commit/c59e20d7d50370a505ef405299005fb65f0aead2
  - [x] NPC mobspawns (citizens)
    - [x] Base aggro system
    - [x] Aggro mechanics
- [x] **Player Data**
  - [x] Persistent player data
  - [x] Currency system
  - [x] Leveling: https://github.com/Goldiriath/Goldiriath/issues/7
  - [x] Health system
    - [x] Store health in PlayerData
    - [x] Override default Minecraft health behaviour.
  - [x] Implement Scoreboards display
    - [x] Add more stuff to Scoreboards
- [x] **Dialogs**
  - [x] Implement dialogs base (loading/parsing)
  - [x] Implement Citizens trigger
  - [x] Implement dialog actions
    - [x] Implement _option_
      - [x] Implement basic option loading/parsing
    - [x] Implement _out_
    - [x] Implement _note_
  - [x] Implement requirements
  - [x] Implement dialog action
  - [x] Implement dialog playerdata
- [x] **Custom items**
  - [x] Implement ItemFactory  https://github.com/Goldiriath/Goldiriath/commit/1393e16315e9334cb3c131c0c268e0e84de9d9ed
  - [x] Make items customizable in a config. https://github.com/Goldiriath/Goldiriath/commit/1ee535a65484067785670abb99a9048740033f58
  - [x] Implement damage modifiers
  - [x] Item enchantments https://github.com/Goldiriath/Goldiriath/commit/a4850252c0dd0b1acffb3244f3fdb8a22f659be6
